### ISSUE TITLE
Limit the number of items shown in 'All' filter

### ISSUE THREAD

**Issue by wihodges** [giotiskl/filterizr#112]
Is there an easy way to set a number on how many filtr-items show up for particular data-category. For instance, I set the filterizr for 'all' on init, but would only like to show the first 10 or so for this data-category, for all the other categories, I would like to display as many as there are.

I would say I could string up something in the callbacks to count, but callbacks don't seem to be working...

**Comment by giotiskl** [comment]
You can try callbacks by updating to v2.

**Comment by pmochine** [comment]
@giotiskl I was also looking for a solution to limit my output for "all". Since I'm using Vue I can easily change the array input, however with that filterizr starts to bug...

I tried the CSS solution however, it's also not working since the height of the overall container will be calculated as if the elements would be there. 

That means that the solution doesn't work 😅

And callbacks are not a good choice either.
