### ISSUE TITLE
Preventing items from being included in the "all" category

### ISSUE THREAD

**Issue by Naman1689** [giotiskl/filterizr#122]
Hello,

First i want to thank you for the great work.
Just need to know what data-category to set or what code do i need to write if i do not want to include a filter-item in all category.

**Comment by giotiskl** [comment]
@Naman1689 all items are included under `all`, that is the point of this category (which essentially means applying no filter).

If you do not wish this functionality you can simply skip having an `all` filter, or you can simply make your own `all` filter but instead of pointing it to `data-category="all"` do something like `<button data-category="1, 2, 4, 5">All</button>` That way you would render everything except for category 3 when clicking on your custom "All" button.
