### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by blitzen12** [giotiskl/Filterizr#2]
Hi,

I wondering if you could help me with this. 

Seems like the error is on line 284 `subArrays[self._mainArray[i]._category[p]].push(self._mainArray[i])`

I use string of category ex. `data-category="Chinse, Single"`

Thanks.

**Comment by Codeshark-NET** [comment]
I'm experiencing the same issue. Can't seem to work around it, even by not using CSV.

**Comment by giotiskl** [comment]
Hello guys, this is probably happening because at the moment data-category is supposed to accept integers as an argument, you can't divide your elements into categories by strings.
You will have to categorise your items as
`data-category="1, 2"`
where 1 is Chinse and 2 is Single.
I might add string support in a future update.

**Comment by Codeshark-NET** [comment]
Tried changing all values to int, such as: `data-category="14, 1, 3"`.
Same issue still occurs. Any pointers?

`Uncaught TypeError: Cannot read property 'push' of undefined`

**Comment by giotiskl** [comment]
You are not skipping any numbers are you? that is you have 14 categories, 1-14?
Because the order you put them in doesn't matter but your available categories shouldn't be for example "1, 2, 3, 14, 28"

**Comment by Codeshark-NET** [comment]
Nope. The numbers aren't ordered, but was using 0-21. Just increased the index to see if it would make a difference, no such luck. 
I'm using a List<int>, and getting the FindIndex to define the categories. (c#).

I'd love to share you the entire code, but I'm a bit under time pressure right now, so perhaps at a later point. 

Here's one of the items though:
`
<div class="grid-wrap">
...
<div class="col-sm-6 col-md-6 filtr-item " data-category="15, 13" data-sort="value">
	<div class="case-wrap">
		<img src="//placehold.it/600x380?text=Case+background" alt="Client" />
		<h2>Description</h2>
		<h4>Client</h4>
		<a href="#" class="overlay"></a>
	</div>
</div>
...
</div>
`

Script:
`
    //Default options
    var options = {
        animationDuration: 0.5, //in seconds
        filter: 'all', //Initial filter
        delay: 0, //Transition delay in ms
        easing: 'ease-out',
        selector: '.grid-wrap',
        setupControls: false
    }
    var filterizd = $('.grid-wrap').filterizr(options);
`

**Comment by giotiskl** [comment]
Yup, there you go I think I got your problem... Do not use indexes 0-21, use 1-21 instead.
I have made it so that the first category must be 1 and increase your indexes from then on!

**Comment by Codeshark-NET** [comment]
I tried to change the index, so that it had a +1 in my code, but that didn't solve it - as i mentioned above. So no solution yet I'm afraid.

**Comment by giotiskl** [comment]
As long as you are using indexes starting from 1 and onwards (without skipping) I do not see what the cause would be, we could perhaps have a look at your code together when you have time. For many working examples of Filterizr you can also check the source code of its (website)[http://yiotis.net/filterizr]

**Comment by Codeshark-NET** [comment]
Thanks, that's very generous. I think I'll start over a little later, see if the problem remains. Otherwise I might take you up on that. :) Have a nice day.

**Comment by giotiskl** [comment]
Sure, make sure to keep me posted and if you wish to feature your project on Filterizr's website, I'd be more than glad to do so!

**Comment by daneloctober** [comment]
Hi!

I just finished debugging a problem that has been "bugging" me for hours on end (same error as Codeshark-NET mentioned). In the end, the only problem was I didn't include a space after the comma when putting the values for the data-category attribute. Is that something you could mitigate? Or is that something we just have to watch out for and remember?

**Comment by giotiskl** [comment]
@daneloctober very nice observation danel, I actually wasn't able to figure out this might have been the problem when we were discussing this issue with @Codeshark-NET. This happens because for multiple categories filterizr parses the integers using string.split using ", " as the delimiter (with a space character). 
This could be changed in an upcoming patch by giving the user the ability to override the default delimiter in the options. However, for the time being it is something that is fixed and you will have to look out for it until further notice.

**Comment by arkid** [comment]
Please make the data-category accept strings and be more flexible with integer input.   It makes setting up for a dynamic cms populated set of content more time consuming to have to handle the data like this with the current restrictions.

**Comment by manandharv** [comment]
**data-category="1, 2, 3**" in my case not line **data-category="1,2,3"** 
A space causing the problem :laos:

**Comment by rddm2bb** [comment]
I tried to install filterizr today. I set up the items with the class filtr-item and data-category="1".
I tried $(myselector).filterizr('shuffle'); and got the error:
Uncaught TypeError: Cannot read property 'push' of undefined
    at ht.fn.init._makeSubarrays

**Comment by aburkhalter15** [comment]
Hi there,

I am trying out filterizr in an ASP.net application. The data that I would like to sort is being pulled in from an API. Here is how I am setting up my data-category in jQuery: 

`$("#houseinfo-beds").attr("data-category" + data.House.Bathrooms);`
^This is within a ajax success function.

I am getting the following error: Uncaught TypeError: Cannot read property 'split' of undefined

Could this error be because of how I am setting the data-category? The data is supposed to be coming in as integers.

Thank you
