### ISSUE TITLE
Uncaught TypeError: Cannot read property 'outerWidth' of undefined 

### ISSUE THREAD

**Issue by manandharv** [giotiskl/Filterizr#40]
- On **Every pages** except of where **filterizr** is called.

![filtrz](https://cloud.githubusercontent.com/assets/11584837/21220650/0113d74a-c2e2-11e6-83b2-d543aa890a5c.PNG)

Using on Wordpress site

**Comment by x4kep** [comment]
Have same problem, on desktop it works, but when i get js files with bower directory this error popup (outerWidth underfined)

**Comment by manandharv** [comment]
@x4kep thanks for the reply but while i include jQuery 1.12.0 still same error occur.

**Comment by Triloworld** [comment]
Reopen because i found error. This is sad but if someone forgot to add class 'filtr-item' to child of container and initialize filterizr then this will show on. This must go silently or use default - first level child of container. After all, jQuery can add all needed class so it will simplify instalation process and less error occur ;)

**Comment by AsjadRex** [comment]
I also faced this issue today. Calling the function on a specific page is the last option.

i used this code for body specific class 'has-filterizr' with following call in script.js
if($('body.has-filterizr').length > 0){
        var filterizd = $('.filtr-container').filterizr();
      }

**Comment by jrxpress** [comment]
thank you AsjadRex .. it works 👍

**Comment by AsjadRex** [comment]
@jrxpress Glad it helped!
