### ISSUE TITLE
Possible to have filter url as the browser url?

### ISSUE THREAD

**Issue by rvadnal** [giotiskl/Filterizr#51]
Hi,

I have a filter structure which goes like this:
<ul class="simplefilter" role="group">
     <li class="btn btn-primary active" data-filter="all">All</li>
     <li class="btn btn-primary" data-filter="1">Filter 1</li>
     <li class="btn btn-primary" data-filter="2">Filter 2</li>
     <li class="btn btn-primary" data-filter="3">Filter 3</li>
     <li class="btn btn-primary" data-filter="4">Filter 4</li>
     <li class="btn btn-primary" data-filter="5">Filter 5</li>
     <li class="btn btn-primary" data-filter="5">Filter 6</li>
</ul>

I want to know if there's a way in which the browser can reflect the URL of the active tab, i.e. www.sampleurl.com/filter-1 instead of www.sampleurl.com when I click on <li class="btn btn-primary" data-filter="1">Filter 1</li>.

**Comment by mdisseny** [comment]
That would be nice! This is how I made it, I'm not a jQuery expert though...

```
// Get URL parameters
function GetURLParameter(sParam) {
    var sPageURL = window.location.search.substring(1);
    var sURLVariables = sPageURL.split('&');
    for (var i = 0; i < sURLVariables.length; i++) 
    {
        var sParameterName = sURLVariables[i].split('=');
        if (sParameterName[0] == sParam) 
        {
            return sParameterName[1];
        }
    }
}​
        
// Get the parameter you want & check if it's defined
var cat = GetURLParameter('cat');
if(cat == null) { cat = 'all' };
        
// Set up the options
options = {
   filter: cat
}
        
// Call the constructor
var filterizd = $('.filtr-container').filterizr(options);
```

Then you'll be able to access:

sampleurl.com or sampleurl.com/?cat=all => Show all
sampleurl.com/?cat=1 => Show filter 1
sampleurl.com/?cat=2 => Show filter 2
...

Hope this helps. Please, correct me if I'm wrong. Cheers!

**Comment by xileftenurb** [comment]
I did something similar, but I wanted the url to update itself as I changed the filter, And I wanted it to work with my group-filter feature (see #61 )
I needed the data send in the onFilteringStart callback (another feature add in pullrequest #61 ) to be able to update it as it change.

I personnaly saved it in a query string, but you could save it in the url as easily.

for your specific use case, it would look like this :

    var filterizd = $('.filtr-container').filterizr({
        //to get the url at page opening
        filter : window.location.path.split("/").slice(-1)[0],
            onFilteringStart : function (previousCategory, newCategory) {
            //note that these param are only available in my pullrequest. but you could find the information direcly by parsing your HTML. it is only a bit more of a pain.
             history.replaceState({}, "filter", "/base-url/" + newCategory)
        }
    });

**Comment by giotiskl** [comment]
@rvadnal closing the issue, considering it resolved. If not, please let us know.

**Comment by kaltrinemehmeti** [comment]
@giotiskl  Please help me with this issue I did like this but it didnt work the filter. So i want from my home page to click the button for specific filter to open the filter page and to be active that filter, because always it opens ALL

// Get URL parameters
function GetURLParameter(sParam) {
    var sPageURL = window.location.search.substring(1);
    var sURLVariables = sPageURL.split('&');
    for (var i = 0; i < sURLVariables.length; i++)
    {
        var sParameterName = sURLVariables[i].split('=');
        if (sParameterName[0] == sParam)
        {
            return sParameterName[1];
        }
    }
}​
// Get the parameter you want & check if it's defined
var cat = GetURLParameter('cat');
if(cat == null) { cat = 'all' };


// Default options
var options = {
  animationDuration: 0.5, // in seconds
  filter:  cat, // Initial filter
  callbacks: {
    onFilteringStart: function() { },
    onFilteringEnd: function() { },
    onShufflingStart: function() { },
    onShufflingEnd: function() { },
    onSortingStart: function() { },
    onSortingEnd: function() { }
  },
  controlsSelector: '', // Selector for custom controls
  delay: 0, // Transition delay in ms
  delayMode: 'progressive', // 'progressive' or 'alternate'
  easing: 'ease-out',
  filterOutCss: { // Filtering out animation
    opacity: 0,
    transform: 'scale(0.5)'
  },
  filterInCss: { // Filtering in animation
    opacity: 0,
    transform: 'scale(1)'
  },
  layout: 'sameSize', // See layouts
  multifilterLogicalOperator: 'or',
  selector: '.filtr-container',
  setupControls: true // Should be false if controlsSelector is set
}
// You can override any of these options and then call...
var filterizd = $('.filtr-container').filterizr(options);
// If you have already instantiated your Filterizr then call...
filterizd.filterizr('setOptions', options);

// active class for controls
$('.filtr-controls').on('click','span',function(){
    $('.filtr-controls').find('span').removeClass('active');
    $(this).addClass('active');
});

**Comment by maynor96** [comment]
Modify the @mdisseny code a bit, because the filtering is done correctly but the lists do not change their status to "active", elaborate the following code and work perfectly:

`function GetURLParameter(sParam) {
	var sPageURL = window.location.search.substring(1);
	var sURLVariables = sPageURL.split('&');
	for (var i = 0; i < sURLVariables.length; i++) {
		var sParameterName = sURLVariables[i].split('=');
		if (sParameterName[0] == sParam) {
			return sParameterName[1];
		}
	}
}

// Get the parameter you want & check if it's defined
var cat = GetURLParameter('cat');
if (cat != null) {
	cat = parseInt(cat);
	$('.filterizr-filter li:nth-child(' + (cat) + ')').click();
}`

Regards!

**Comment by brandlewco** [comment]
has anyone done this with vanilla JS

**Comment by brandlewco** [comment]
it appears the code base has been refactored for ES6 since this discussion. Are there any current vanilla examples on how to achieve this?
