### ISSUE TITLE
Filters that works with two select type

### ISSUE THREAD

**Issue by freeenk** [giotiskl/Filterizr#81]
Hello, i'm trying to filter my list with a combination of two select: one for category and one for sorting.
(In particular i've shop types and cities and the user will be able to filter: all 'Bars' of  'Toronto'). 
I've read issue #16, but i think that answered solution it refers on a old version of this script. 

Thanks in advance,
Francesco

**Comment by giotiskl** [comment]
If I understand correctly you would like to use a select input instead of buttons to trigger the filtering.

Then you simply have to call the `filterizr('filter', category)` method on your Filterizr instance.

If you have a select `<select class="fltr-select" ...>...</select>` then you would have to do this within the `onchange` event:
```
var filterizr = $('.filtr-container').filterizr();

$('.filtr-select').on('change', function(event) {
   var val = $(event.currentTarget).val();
   filterizr.filterizr('filter', val);
});
```

**Comment by freeenk** [comment]
Thanks @giotiskl for fast reply, now works like a charm!

Maybe for future release it will be great have a options for choice type of html filter (li, div, select, ...). 

Thanks again,
Francesco

**Comment by bradallenfisher** [comment]
any way to get this to work with data-multifilter so i can use "and" rather than "or" for multiple select lists? Like filter once, then filter again to a smaller subset of the first filtered items.
